/**
 * Mir Drualga Common For C
 * Copyright (C) 2020  Mir Drualga
 *
 * This file is part of Mir Drualga Common For C.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Additional permissions under GNU Affero General Public License version 3
 *  section 7
 *
 *  If you modify this Program, or any covered work, by linking or combining
 *  it with any program (or a modified version of that program and its
 *  libraries), containing parts covered by the terms of an incompatible
 *  license, the licensors of this Program grant you additional permission
 *  to convey the resulting work.
 */

#ifndef MDC_C_OBJECT_INTERNAL_INTEGER_OBJECT_INTEGER_OBJECT_DECLARE_MACROS_H_
#define MDC_C_OBJECT_INTERNAL_INTEGER_OBJECT_INTEGER_OBJECT_DECLARE_MACROS_H_

#include "../object_declare_macros.h"
#include "integer_object_name_macros.h"
#include "integer_object_typedef.h"

/**
 * Initialize / Deinitialize
 */

#define MDC_DECLARE_INTEGER_INIT_DEFAULT(T_IntT) \
    MDC_DECLARE_OBJECT_INIT_DEFAULT(T_IntT)

#define MDC_DECLARE_INTEGER_INIT_FROM_VALUE(T_IntT) \
    MDC_DECLARE_OBJECT_INIT_FROM(T_IntT, MDC_T(T_IntT))

#define MDC_DECLARE_INTEGER_INIT_COPY(T_IntT) \
    MDC_DECLARE_OBJECT_INIT_COPY(T_IntT)

#define MDC_DECLARE_INTEGER_INIT_MOVE(T_IntT) \
    MDC_DECLARE_OBJECT_INIT_MOVE(T_IntT)

#define MDC_DECLARE_INTEGER_DEINIT(T_IntT) \
    MDC_DECLARE_OBJECT_DEINIT(T_IntT)

/**
 * Assignment
 */

#define MDC_DECLARE_INTEGER_ASSIGN_COPY(T_IntT) \
    MDC_DECLARE_OBJECT_ASSIGN_COPY(T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_MOVE(T_IntT) \
    MDC_DECLARE_OBJECT_ASSIGN_MOVE(T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_ADD(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_ADD(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_SUBTRACT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_SUBTRACT(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_MULTIPLY(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_MULTIPLY(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_DIVIDE(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_DIVIDE(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_MODULO(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_MODULO(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_BITWISE_AND(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_BITWISE_AND(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_BITWISE_OR(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_BITWISE_OR(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_BITWISE_XOR(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_BITWISE_XOR(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_BITWISE_LEFT_SHIFT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_BITWISE_LEFT_SHIFT(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_ASSIGN_BITWISE_RIGHT_SHIFT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ASSIGN_BITWISE_RIGHT_SHIFT(T_IntT, T_IntT)

/**
 * Increment / Decrement
 */

#define MDC_DECLARE_INTEGER_PRE_INCREMENT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_PRE_INCREMENT(T_IntT)

#define MDC_DECLARE_INTEGER_PRE_DECREMENT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_PRE_DECREMENT(T_IntT)

#define MDC_DECLARE_INTEGER_POST_INCREMENT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_POST_INCREMENT(T_IntT)

#define MDC_DECLARE_INTEGER_POST_DECREMENT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_POST_DECREMENT(T_IntT)

/**
 * Arithmetic
 */

#define MDC_DECLARE_INTEGER_UNARY_PLUS(T_IntT) \
    MDC_DECLARE_OBJECT_UNARY_PLUS(MDC_T(T_IntT), T_IntT)

#define MDC_DECLARE_INTEGER_UNARY_PLUS_CONST(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_UNARY_PLUS_CONST(T_IntT)

#define MDC_DECLARE_INTEGER_UNARY_MINUS(T_IntT) \
    MDC_DECLARE_OBJECT_UNARY_MINUS(MDC_T(T_IntT), T_IntT)

#define MDC_DECLARE_INTEGER_UNARY_MINUS_CONST(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_UNARY_MINUS_CONST(T_IntT)

#define MDC_DECLARE_INTEGER_ADD(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_ADD(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_SUBTRACT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_SUBTRACT(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_MULTIPLY(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_MULTIPLY(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_DIVIDE(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_DIVIDE(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_MODULO(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_MODULO(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_NOT(T_IntT) \
    MDC_DECLARE_OBJECT_BITWISE_NOT(MDC_T(T_IntT), T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_NOT_CONST(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_BITWISE_NOT_CONST(T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_AND(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_BITWISE_AND(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_OR(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_BITWISE_OR(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_XOR(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_BITWISE_XOR(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_LEFT_SHIFT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_BITWISE_LEFT_SHIFT(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_BITWISE_RIGHT_SHIFT(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_BITWISE_RIGHT_SHIFT(T_IntT, T_IntT)

/**
 * Logical
 */

#define MDC_DECLARE_INTEGER_LOGICAL_NOT(T_IntT) \
    MDC_DECLARE_OBJECT_LOGICAL_NOT(bool, T_IntT)

#define MDC_DECLARE_INTEGER_LOGICAL_NOT_CONST(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_LOGICAL_NOT_CONST(T_IntT)

#define MDC_DECLARE_INTEGER_LOGICAL_AND(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_LOGICAL_AND(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_LOGICAL_OR(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_LOGICAL_OR(T_IntT, T_IntT)

/**
 * Comparison
 */

#define MDC_DECLARE_INTEGER_EQUAL(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_EQUAL(T_IntT, T_IntT)

#define MDC_DECLARE_INTEGER_COMPARE(T_IntT) \
    MDC_DECLARE_OBJECT_DEFAULT_COMPARE(T_IntT, T_IntT)

/**
 * General Functions
 */

#define MDC_DECLARE_INTEGER_SWAP(T_IntT) \
    MDC_DECLARE_OBJECT_SWAP(T_IntT)

#define MDC_INTERNAL_DECLARE_UNSIGNED_INTEGER_FUNCTIONS(T_IntT) \
    MDC_DECLARE_INTEGER_INIT_DEFAULT(T_IntT) \
    MDC_DECLARE_INTEGER_INIT_FROM_VALUE(T_IntT) \
    MDC_DECLARE_INTEGER_INIT_COPY(T_IntT) \
    MDC_DECLARE_INTEGER_INIT_MOVE(T_IntT) \
    MDC_DECLARE_INTEGER_DEINIT(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_COPY(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_MOVE(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_ADD(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_SUBTRACT(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_MULTIPLY(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_DIVIDE(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_MODULO(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_BITWISE_AND(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_BITWISE_OR(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_BITWISE_XOR(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_BITWISE_LEFT_SHIFT(T_IntT) \
    MDC_DECLARE_INTEGER_ASSIGN_BITWISE_RIGHT_SHIFT(T_IntT) \
    MDC_DECLARE_INTEGER_PRE_INCREMENT(T_IntT) \
    MDC_DECLARE_INTEGER_PRE_DECREMENT(T_IntT) \
    MDC_DECLARE_INTEGER_POST_INCREMENT(T_IntT) \
    MDC_DECLARE_INTEGER_POST_DECREMENT(T_IntT) \
    MDC_DECLARE_INTEGER_UNARY_PLUS(T_IntT) \
    MDC_DECLARE_INTEGER_UNARY_PLUS_CONST(T_IntT) \
    MDC_DECLARE_INTEGER_ADD(T_IntT) \
    MDC_DECLARE_INTEGER_SUBTRACT(T_IntT) \
    MDC_DECLARE_INTEGER_MULTIPLY(T_IntT) \
    MDC_DECLARE_INTEGER_DIVIDE(T_IntT) \
    MDC_DECLARE_INTEGER_MODULO(T_IntT) \
    MDC_DECLARE_INTEGER_BITWISE_NOT_CONST(T_IntT) \
    MDC_DECLARE_INTEGER_BITWISE_AND(T_IntT) \
    MDC_DECLARE_INTEGER_BITWISE_OR(T_IntT) \
    MDC_DECLARE_INTEGER_BITWISE_XOR(T_IntT) \
    MDC_DECLARE_INTEGER_BITWISE_LEFT_SHIFT(T_IntT) \
    MDC_DECLARE_INTEGER_BITWISE_RIGHT_SHIFT(T_IntT) \
    MDC_DECLARE_INTEGER_LOGICAL_NOT(T_IntT) \
    MDC_DECLARE_INTEGER_LOGICAL_NOT_CONST(T_IntT) \
    MDC_DECLARE_INTEGER_LOGICAL_AND(T_IntT) \
    MDC_DECLARE_INTEGER_LOGICAL_OR(T_IntT) \
    MDC_DECLARE_INTEGER_EQUAL(T_IntT) \
    MDC_DECLARE_INTEGER_COMPARE(T_IntT)

#define MDC_INTERNAL_DECLARE_DLLEXPORT_UNSIGNED_INTEGER_FUNCTIONS(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_INIT_DEFAULT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_INIT_FROM_VALUE(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_INIT_COPY(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_INIT_MOVE(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_DEINIT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_COPY(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_MOVE(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_ADD(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_SUBTRACT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_MULTIPLY(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_DIVIDE(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_MODULO(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_BITWISE_AND(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_BITWISE_OR(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_BITWISE_XOR(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_BITWISE_LEFT_SHIFT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ASSIGN_BITWISE_RIGHT_SHIFT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_PRE_INCREMENT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_PRE_DECREMENT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_POST_INCREMENT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_POST_DECREMENT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_UNARY_PLUS(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_UNARY_PLUS_CONST(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_ADD(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_SUBTRACT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_MULTIPLY(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_DIVIDE(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_MODULO(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_BITWISE_NOT_CONST(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_BITWISE_AND(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_BITWISE_OR(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_BITWISE_XOR(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_BITWISE_LEFT_SHIFT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_BITWISE_RIGHT_SHIFT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_LOGICAL_NOT(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_LOGICAL_NOT_CONST(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_LOGICAL_AND(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_LOGICAL_OR(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_EQUAL(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_COMPARE(T_IntT)

#define MDC_INTERNAL_DECLARE_SIGNED_INTEGER_FUNCTIONS(T_IntT) \
    MDC_INTERNAL_DECLARE_UNSIGNED_INTEGER_FUNCTIONS(T_IntT) \
    MDC_DECLARE_INTEGER_UNARY_MINUS(T_IntT) \
    MDC_DECLARE_INTEGER_UNARY_MINUS_CONST(T_IntT)

#define MDC_INTERNAL_DECLARE_DLLEXPORT_SIGNED_INTEGER_FUNCTIONS(T_IntT) \
    MDC_INTERNAL_DECLARE_DLLEXPORT_UNSIGNED_INTEGER_FUNCTIONS(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_UNARY_MINUS(T_IntT) \
    DLLEXPORT MDC_DECLARE_INTEGER_UNARY_MINUS_CONST(T_IntT)

#define MDC_INTERNAL_DECLARE_UNSIGNED_INTEGER(T_IntT) \
    MDC_T_DECLARE_TYPEDEFS(T_IntT) \
    MDC_INTERNAL_DECLARE_UNSIGNED_INTEGER_FUNCTIONS(T_IntT)

#define MDC_INTERNAL_DECLARE_DLLEXPORT_UNSIGNED_INTEGER(T_IntT) \
    MDC_T_DECLARE_TYPEDEFS(T_IntT) \
    MDC_INTERNAL_DECLARE_DLLEXPORT_UNSIGNED_INTEGER_FUNCTIONS(T_IntT)

#define MDC_INTERNAL_DECLARE_SIGNED_INTEGER(T_IntT) \
    MDC_T_DECLARE_TYPEDEFS(T_IntT) \
    MDC_INTERNAL_DECLARE_SIGNED_INTEGER_FUNCTIONS(T_IntT)

#define MDC_INTERNAL_DECLARE_DLLEXPORT_SIGNED_INTEGER(T_IntT) \
    MDC_T_DECLARE_TYPEDEFS(T_IntT) \
    MDC_INTERNAL_DECLARE_DLLEXPORT_SIGNED_INTEGER_FUNCTIONS(T_IntT)

#endif /* MDC_C_OBJECT_INTERNAL_INTEGER_OBJECT_INTEGER_OBJECT_DECLARE_MACROS_H_ */
